# Generated by Django 3.0 on 2019-12-13 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='despesa',
            options={'verbose_name_plural': 'despesas'},
        ),
    ]
